theme: jekyll-theme-minimal
title: Shripad Sinari
show_downloads: false
address: |
 <br/>
 seomewhere over the rainbow <br/>
 bluebirds, sing, 85659
email: xxx@gmail.com
phone: xxx-xxx-xxxx
education: | 
 <br/>
 M.Sc. Biostatistics <br/>
 M.Sc. Mathematics <br/>
institution: |
 The University of Arizona <br/>
 Tucson, Arizona

