theme: jekyll-theme-minimal
title: Shripad Sinari
show_downloads: false
address: |
 <br/>
 seomewhere over the rainbow <br/>
 bluebirds, sing, 85659
email: xxx@gmail.com
phone: xxx-xxx-xxxx
education: | 
 <br/>
 M.Sc. Biostatistics <br/>
 M.Sc. Mathematics <br/>
institution: |
 The University of Arizona <br/>
 Tucson, Arizona
experience: |
 <b>Statistician: Jan 2013 to present</b><br/>
 <i>BIO5 Institute, The University of Arizona.</i><br/>
 Provides statistical and computing expertise 
 in basic, applied and clinical research.<br/>
 <br/>
 <b>Staff Scientist: Nov 2011 to Jan 2013</b><br/>
 <i>R&D Support, Life Technologies 
 Foster City, California.</i><br/>
 Provided diagnostic and analytical support
 for Ion Torrent Technology.<br/>
 <br/>
 <b>Bioinformatician: Mar 2008 to Nov 2011</b> 
 <i>Translational Genomics Research Institute 
 Phoenix, Arizona.</i><br/>
 Developed analysis workflows and
 structural variation algorithms.

