remote_theme:  pages-themes/minimal

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-seo-tag
show_downloads: false
title: Shripad Sinari
address: |
 <br/>
 seomewhere over the rainbow <br/>
 bluebirds, sing, 85659
email: |
  <a href=""mailto:shripad.sinari@gmail.com"">
  <span style="color: \#00629b; font-size: 1.5rem;">
  <i class="fal fa-envelope fa-1x"></i>
  </span>
  </a>
phone: |
  <a href="tel:+1 (520) 245-6292">
  <span style="color: \#00629b; font-size: 0.75rem; margin-left:15px;">
  <i class="fas fa-phone fa-2x"></i>
  </span>
  </a>
linkedIn:  |
  <a href="https://linkedin.com/in/shripad-sinari">
  <span style="color: \#00629b; ; margin-left:20px;">             
  <i class="fab fa-linkedin-in fa-2x"></i>
  </span>
  </a>
github: |
  <a href="https://github.com/ssinari">
  <span style="color: \#00629b; ; margin-left:20px;">
  <i class="fab fa-github fa-2x"></i>
  </span>
  </a>
scholar: |
  <a href="https://scholar.google.com/citations?user=avKGegEAAAAJ&hl=en">
  <span style="color: \#00629b; ; margin-left:20px;">
  <i class="ai ai-google-scholar ai-2x"></i>
  </span>
  </a>
skills: |
  <br/>
  <b>Data types handled:</b>
  Longitudinal data, High-throughput omics data, public health and clinical data.
  <br/>
  <b> Statistical techniques:</b>
  Generalized Linear Models (GLM), Mixed-Models, Survival analysis, Statistical Machine Learning, Bayesian data analysis, Compositional data analysis (CoDA).
  <br/>
  <b> Data analysis software:</b>
  SAS, R, ecosystem of packages Bioconductor, tidyverse, mlverse, keras, TensorFlow.
  <br/>
  <b> Bayesian computing: </b>
  OpenBUGS, JAGS, Stan.
  <br/>
  <b> Databases:</b>
  REDCap, RODBC for interfacing with other databases.
  <br/>
  <b> Visualization:</b>
  ggplot2, shinyapps, flexdashboards.



