theme: jekyll-theme-minimal
title: Shripad Sinari
show_downloads: false
address: |
 <br/>
 12151 N Meditation Drive <br/>
 Marana, Arizona, 85658
education: | 
 <br/>
 M.Sc. Biostatistics <br/>
 The University of Arizona, Tucson, Arizona <br/>
 M.Sc. Mathematics <br/>
 The University of Arizona, Tucson, Arizona
Summary: |
 Experienced biostatistician with strong applied statistics and computing background. 
 Hands on experience in writing statistical analysis plans (SAP), 
 designing experiments and providing insightful, actionable reports. 
 Effective at communicating complex results to diverse audiences, and 
 ensuring understanding of requirements at all levels of a cross functional team 
 for smooth collaboration and timely execution of projects.
