theme: jekyll-theme-minimal
title: Shripad Sinari
description: |
**address:**

12151 N Meditation Drive 

Marana, Arizona, 85658

**Summary:**

Experienced biostatistician with strong applied statistics and computing background. Hands on experience in writing statistical analysis plans (SAP), designing experiments and providing insightful, actionable reports. Effective at communicating complex results to diverse audiences, and ensuring understanding of requirements at all levels of a cross functional team for smooth collaboration and timely execution of projects.
