theme: jekyll-theme-minimal
title: Shripad Sinari
show_downloads: false
address: |
 <br/>
 seomewhere over the rainbow <br/>
 bluebirds, sing, 85659
email: <a href="mailto:shripad.sinari@gmail.com">Email</a>
website: <a href="https://workwithcarolyn.com/">Site</a>
linkedIn: <a href="https://www.linkedin.com/in/shripad-sinari-9a48801/">LinkedIn</a>
gitHub: <a href="https://github.com/ssinari/">Github</a>
education: | 
 <br/>
 M.Sc. Biostatistics <br/>
 M.Sc. Mathematics <br/>
institution: |
 The University of Arizona <br/>
 Tucson, Arizona
experience: |
 <br/>
 <b>Statistician:</b> Jan 2013 to present<br/>
 <i>BIO5 Institute, The University of Arizona.</i><br/>
 Provides statistical and computing expertise 
 in basic, applied and clinical research.<br/>
 <br/>
 <b>Staff Scientist:</b> Nov 2011 to Jan 2013<br/>
 <i>R&D Support, Life Technologies 
 Foster City, California.</i><br/>
 Provided diagnostic and analytical support
 for Ion Torrent Technology.<br/>
 <br/>
 <b>Bioinformatician:</b> Mar 2008 to Nov 2011<br/> 
 <i>Translational Genomics Research Institute 
 Phoenix, Arizona.</i><br/>
 Developed analysis workflows and
 structural variation algorithms.

