theme: jekyll-theme-minimal
title: Shripad Sinari
show_downloads: false
address: |
 <br/>
 seomewhere over the rainbow <br/>
 bluebirds, sing, 85659
email: xxx@gmail.com
phone: xxx-xxx-xxxx
education: | 
 <br/>
 M.Sc. Biostatistics <br/>
 M.Sc. Mathematics <br/>
institution: |
 The University of Arizona <br/>
 Tucson, Arizona
experience: |
 Statistician: Jan 2013 to present<br/>
 <i>BIO5 Institute, The University of Arizona.</i><br/>
 Provides statistical and computing expertise<br/> 
 in basic, applied and clinical research.<br/>
 <br/>
 Staff Scientist: Nov 2011 to Jan 2013<br/>
 <i>R&D Support, Life Technologies<br/> 
 Foster City, California.</i><br/>
 Provided diagnostic and analytical support<br/>
 for Ion Torrent Technology.<br/>
 <br/>
 Bioinformatician: Mar 2008 to Nov 2011 
 <i>Translational Genomics Research Institute<br/> 
 Phoenix, Arizona.</i><br/>
 Developed analysis workflows and <br/>
 structural variation algorithms.

