theme: jekyll-theme-minimal
title: Shripad Sinari
show_downloads: false
address: |
 <br/>
 12151 N Meditation Drive <br/>
 Marana, Arizona, 85658
education: | 
 <br/>
 M.Sc. Biostatistics <br/>
 M.Sc. Mathematics <br/>
institution: |
 <br/>
 The University of Arizona <br/>
 Tucson, Arizona

